using System.Windows.Input;
using NeoEdit.GUI.Common;

namespace NeoEdit.TextEditor
{
	enum TextEditCommand
	{
		None,
		[KeyGesture(Key.N, ModifierKeys.Control)] [KeyGesture(Key.T, ModifierKeys.Control)] File_New,
		[KeyGesture(Key.O, ModifierKeys.Control)] File_Open,
		File_OpenCopiedCutFiles,
		[KeyGesture(Key.S, ModifierKeys.Control)] File_Save,
		File_SaveAs,
		[KeyGesture(Key.F4, ModifierKeys.Control)] [KeyGesture(Key.W, ModifierKeys.Control)] File_Close,
		[KeyGesture(Key.F5)] File_Refresh,
		File_Revert,
		File_InsertFiles,
		File_CopyPath,
		File_CopyName,
		File_Encoding,
		[KeyGesture(Key.B, ModifierKeys.Control | ModifierKeys.Alt)] File_BinaryEditor,
		File_Exit,
		[KeyGesture(Key.Z, ModifierKeys.Control)] Edit_Undo,
		[KeyGesture(Key.Z, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Redo,
		[KeyGesture(Key.X, ModifierKeys.Control)] Edit_Cut,
		[KeyGesture(Key.C, ModifierKeys.Control)] Edit_Copy,
		[KeyGesture(Key.V, ModifierKeys.Control)] [KeyGesture(Key.V, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Paste,
		[KeyGesture(Key.C, ModifierKeys.Control | ModifierKeys.Shift)] Edit_ShowClipboard,
		[KeyGesture(Key.F, ModifierKeys.Control)]  [KeyGesture(Key.F, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Find,
		[KeyGesture(Key.F3)]  [KeyGesture(Key.F3, ModifierKeys.Shift)] Edit_FindNext,
		[KeyGesture(Key.F3, ModifierKeys.Control)]  [KeyGesture(Key.F3, ModifierKeys.Control | ModifierKeys.Shift)] Edit_FindPrev,
		[KeyGesture(Key.G, ModifierKeys.Control)]  [KeyGesture(Key.G, ModifierKeys.Control | ModifierKeys.Shift)] Edit_GotoLine,
		Edit_GotoColumn,
		Files_Copy,
		Files_Cut,
		Files_Open,
		Files_Delete,
		Files_Timestamp_Write,
		Files_Timestamp_Access,
		Files_Timestamp_Create,
		Files_Timestamp_All,
		Files_Path_Simplify,
		Files_Path_FileName,
		Files_Path_FileNamewoExtension,
		Files_Path_DirectoryName,
		Files_Path_Extension,
		Files_CreateDirectory,
		Files_Information_Size,
		Files_Information_WriteTime,
		Files_Information_AccessTime,
		Files_Information_CreateTime,
		Files_Information_Attributes,
		Files_Information_ReadOnly,
		Files_Checksum_MD5,
		Files_Checksum_SHA1,
		Files_Checksum_SHA256,
		Files_Select_Existing,
		Files_Select_Files,
		Files_Select_Directories,
		Files_Select_Roots,
		Files_RenameKeysToSelections,
		[KeyGesture(Key.U, ModifierKeys.Control)] Data_Case_Upper,
		[KeyGesture(Key.U, ModifierKeys.Control | ModifierKeys.Shift)] Data_Case_Lower,
		Data_Case_Proper,
		Data_Case_Toggle,
		[KeyGesture(Key.H, ModifierKeys.Control)] Data_Hex_ToHex,
		[KeyGesture(Key.H, ModifierKeys.Control | ModifierKeys.Shift)] Data_Hex_FromHex,
		Data_Binary_ToBinary_String_UTF8,
		Data_Binary_ToBinary_String_UTF7,
		Data_Binary_ToBinary_String_UTF16LE,
		Data_Binary_ToBinary_String_UTF16BE,
		Data_Binary_ToBinary_String_UTF32LE,
		Data_Binary_ToBinary_String_UTF32BE,
		Data_Binary_ToBinary_String_Base64,
		Data_Binary_ToBinary_UIntLE_UInt8LE,
		Data_Binary_ToBinary_UIntLE_UInt16LE,
		Data_Binary_ToBinary_UIntLE_UInt32LE,
		Data_Binary_ToBinary_UIntLE_UInt64LE,
		Data_Binary_ToBinary_IntLE_Int8LE,
		Data_Binary_ToBinary_IntLE_Int16LE,
		Data_Binary_ToBinary_IntLE_Int32LE,
		Data_Binary_ToBinary_IntLE_Int64LE,
		Data_Binary_ToBinary_UIntBE_UInt8BE,
		Data_Binary_ToBinary_UIntBE_UInt16BE,
		Data_Binary_ToBinary_UIntBE_UInt32BE,
		Data_Binary_ToBinary_UIntBE_UInt64BE,
		Data_Binary_ToBinary_IntBE_Int8BE,
		Data_Binary_ToBinary_IntBE_Int16BE,
		Data_Binary_ToBinary_IntBE_Int32BE,
		Data_Binary_ToBinary_IntBE_Int64BE,
		Data_Binary_ToBinary_Float_Single,
		Data_Binary_ToBinary_Float_Double,
		Data_Binary_FromBinary_String_Auto,
		Data_Binary_FromBinary_String_UTF8,
		Data_Binary_FromBinary_String_UTF7,
		Data_Binary_FromBinary_String_UTF16LE,
		Data_Binary_FromBinary_String_UTF16BE,
		Data_Binary_FromBinary_String_UTF32LE,
		Data_Binary_FromBinary_String_UTF32BE,
		Data_Binary_FromBinary_String_Base64,
		Data_Binary_FromBinary_UIntLE_UInt8LE,
		Data_Binary_FromBinary_UIntLE_UInt16LE,
		Data_Binary_FromBinary_UIntLE_UInt32LE,
		Data_Binary_FromBinary_UIntLE_UInt64LE,
		Data_Binary_FromBinary_IntLE_Int8LE,
		Data_Binary_FromBinary_IntLE_Int16LE,
		Data_Binary_FromBinary_IntLE_Int32LE,
		Data_Binary_FromBinary_IntLE_Int64LE,
		Data_Binary_FromBinary_UIntBE_UInt8BE,
		Data_Binary_FromBinary_UIntBE_UInt16BE,
		Data_Binary_FromBinary_UIntBE_UInt32BE,
		Data_Binary_FromBinary_UIntBE_UInt64BE,
		Data_Binary_FromBinary_IntBE_Int8BE,
		Data_Binary_FromBinary_IntBE_Int16BE,
		Data_Binary_FromBinary_IntBE_Int32BE,
		Data_Binary_FromBinary_IntBE_Int64BE,
		Data_Binary_FromBinary_Float_Single,
		Data_Binary_FromBinary_Float_Double,
		Data_Base64_ToBase64_UTF8,
		Data_Base64_ToBase64_UTF7,
		Data_Base64_ToBase64_UTF16LE,
		Data_Base64_ToBase64_UTF16BE,
		Data_Base64_ToBase64_UTF32LE,
		Data_Base64_ToBase64_UTF32BE,
		Data_Base64_ToBase64_Binary,
		Data_Base64_FromBase64_Auto,
		Data_Base64_FromBase64_UTF8,
		Data_Base64_FromBase64_UTF7,
		Data_Base64_FromBase64_UTF16LE,
		Data_Base64_FromBase64_UTF16BE,
		Data_Base64_FromBase64_UTF32LE,
		Data_Base64_FromBase64_UTF32BE,
		Data_Base64_FromBase64_Binary,
		Data_DateTime_Insert,
		Data_DateTime_Convert,
		Data_Length,
		Data_Width,
		Data_Trim,
		[KeyGesture(Key.E, ModifierKeys.Control)] Data_EvaluateExpression,
		Data_Series,
		[KeyGesture(Key.D, ModifierKeys.Control)] Data_CopyDown,
		Data_Copy_Count,
		Data_Copy_Min_String,
		Data_Copy_Min_Numeric,
		Data_Copy_Max_String,
		Data_Copy_Max_Numeric,
		Data_Copy_Length_Min,
		Data_Copy_Length_Max,
		Data_Copy_Sum,
		[KeyGesture(Key.R, ModifierKeys.Control)] Data_Repeat,
		Data_InsertGUID,
		Data_InsertRandomNumber,
		Data_Escape_XML,
		Data_Escape_Regex,
		Data_Escape_URL,
		Data_Unescape_XML,
		Data_Unescape_Regex,
		Data_Unescape_URL,
		Data_MD5_UTF8,
		Data_MD5_UTF7,
		Data_MD5_UTF16LE,
		Data_MD5_UTF16BE,
		Data_MD5_UTF32LE,
		Data_MD5_UTF32BE,
		Data_SHA1_UTF8,
		Data_SHA1_UTF7,
		Data_SHA1_UTF16LE,
		Data_SHA1_UTF16BE,
		Data_SHA1_UTF32LE,
		Data_SHA1_UTF32BE,
		Data_SHA256_UTF8,
		Data_SHA256_UTF7,
		Data_SHA256_UTF16LE,
		Data_SHA256_UTF16BE,
		Data_SHA256_UTF32LE,
		Data_SHA256_UTF32BE,
		Sort_String,
		Sort_Numeric,
		Sort_Keys,
		Sort_Reverse,
		Sort_Randomize,
		Sort_SortByLength,
		Sort_Lines_String,
		Sort_Lines_Numeric,
		Sort_Lines_Keys,
		Sort_Lines_Reverse,
		Sort_Lines_Randomize,
		Sort_Lines_SortByLength,
		Sort_Regions_String,
		Sort_Regions_Numeric,
		Sort_Regions_Keys,
		Sort_Regions_Reverse,
		Sort_Regions_Randomize,
		Sort_Regions_SortByLength,
		[KeyGesture(Key.K, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Keys,
		[KeyGesture(Key.D1, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values1,
		[KeyGesture(Key.D2, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values2,
		[KeyGesture(Key.D3, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values3,
		[KeyGesture(Key.D4, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values4,
		[KeyGesture(Key.D5, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values5,
		[KeyGesture(Key.D6, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values6,
		[KeyGesture(Key.D7, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values7,
		[KeyGesture(Key.D8, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values8,
		[KeyGesture(Key.D9, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values9,
		[KeyGesture(Key.D1, ModifierKeys.Control)] Keys_SelectionReplace_Values1,
		[KeyGesture(Key.D2, ModifierKeys.Control)] Keys_SelectionReplace_Values2,
		[KeyGesture(Key.D3, ModifierKeys.Control)] Keys_SelectionReplace_Values3,
		[KeyGesture(Key.D4, ModifierKeys.Control)] Keys_SelectionReplace_Values4,
		[KeyGesture(Key.D5, ModifierKeys.Control)] Keys_SelectionReplace_Values5,
		[KeyGesture(Key.D6, ModifierKeys.Control)] Keys_SelectionReplace_Values6,
		[KeyGesture(Key.D7, ModifierKeys.Control)] Keys_SelectionReplace_Values7,
		[KeyGesture(Key.D8, ModifierKeys.Control)] Keys_SelectionReplace_Values8,
		[KeyGesture(Key.D9, ModifierKeys.Control)] Keys_SelectionReplace_Values9,
		Keys_GlobalFind_Keys,
		Keys_GlobalFind_Values1,
		Keys_GlobalFind_Values2,
		Keys_GlobalFind_Values3,
		Keys_GlobalFind_Values4,
		Keys_GlobalFind_Values5,
		Keys_GlobalFind_Values6,
		Keys_GlobalFind_Values7,
		Keys_GlobalFind_Values8,
		Keys_GlobalFind_Values9,
		Keys_GlobalReplace_Values1,
		Keys_GlobalReplace_Values2,
		Keys_GlobalReplace_Values3,
		Keys_GlobalReplace_Values4,
		Keys_GlobalReplace_Values5,
		Keys_GlobalReplace_Values6,
		Keys_GlobalReplace_Values7,
		Keys_GlobalReplace_Values8,
		Keys_GlobalReplace_Values9,
		Keys_Copy_Keys,
		Keys_Copy_Values1,
		Keys_Copy_Values2,
		Keys_Copy_Values3,
		Keys_Copy_Values4,
		Keys_Copy_Values5,
		Keys_Copy_Values6,
		Keys_Copy_Values7,
		Keys_Copy_Values8,
		Keys_Copy_Values9,
		Keys_Hits_Keys,
		Keys_Hits_Values1,
		Keys_Hits_Values2,
		Keys_Hits_Values3,
		Keys_Hits_Values4,
		Keys_Hits_Values5,
		Keys_Hits_Values6,
		Keys_Hits_Values7,
		Keys_Hits_Values8,
		Keys_Hits_Values9,
		Keys_Misses_Keys,
		Keys_Misses_Values1,
		Keys_Misses_Values2,
		Keys_Misses_Values3,
		Keys_Misses_Values4,
		Keys_Misses_Values5,
		Keys_Misses_Values6,
		Keys_Misses_Values7,
		Keys_Misses_Values8,
		Keys_Misses_Values9,
		Keys_CountstoKeysValues1,
		[KeyGesture(Key.M, ModifierKeys.Control)] SelectMark_Toggle,
		[KeyGesture(Key.A, ModifierKeys.Control)] Select_All,
		Select_Limit,
		[KeyGesture(Key.L, ModifierKeys.Control)] Select_Lines,
		Select_NonEmpty,
		Select_Unique,
		Select_Duplicates,
		Select_Marks,
		Select_FindResults,
		Select_Min_String,
		Select_Min_Numeric,
		Select_Max_String,
		Select_Max_Numeric,
		Select_ExpressionMatches,
		Select_RegExMatches,
		[KeyGesture(Key.D0, ModifierKeys.Alt)] Select_FirstSelection,
		[KeyGesture(Key.Space, ModifierKeys.Alt)]  [KeyGesture(Key.Space, ModifierKeys.Control)] Select_ShowCurrent,
		[KeyGesture(Key.Down, ModifierKeys.Alt)] Select_NextSelection,
		[KeyGesture(Key.Up, ModifierKeys.Alt)] Select_PrevSelection,
		[KeyGesture(Key.Enter, ModifierKeys.Alt)] Select_Single,
		[KeyGesture(Key.OemMinus, ModifierKeys.Alt)] Select_Remove,
		Mark_Selection,
		Mark_FindResults,
		Mark_ClearMarks,
		Mark_LimitToSelection,
		View_Highlighting_None,
		View_Highlighting_CSharp,
		View_Highlighting_CPlusPlus,
		View_Tiles,
	}
}
