using System.Windows.Input;
using NeoEdit.GUI.Common;

namespace NeoEdit.TextEditor
{
	enum TextEditCommand
	{
		None,
		[KeyGesture(Key.N, ModifierKeys.Control)] [KeyGesture(Key.T, ModifierKeys.Control)] File_New,
		[KeyGesture(Key.O, ModifierKeys.Control)] File_Open,
		File_OpenCopied,
		[KeyGesture(Key.S, ModifierKeys.Control)] File_Save,
		File_SaveAs,
		[KeyGesture(Key.F4, ModifierKeys.Control)] [KeyGesture(Key.W, ModifierKeys.Control)] File_Close,
		[KeyGesture(Key.F5)] File_Refresh,
		File_Revert,
		File_InsertFiles,
		File_CopyPath,
		File_CopyName,
		File_Encoding,
		[KeyGesture(Key.B, ModifierKeys.Control | ModifierKeys.Alt)] File_BinaryEditor,
		File_Exit,
		[KeyGesture(Key.Z, ModifierKeys.Control)] Edit_Undo,
		[KeyGesture(Key.Z, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Redo,
		[KeyGesture(Key.X, ModifierKeys.Control)] Edit_Cut,
		[KeyGesture(Key.C, ModifierKeys.Control)] Edit_Copy,
		[KeyGesture(Key.V, ModifierKeys.Control)] [KeyGesture(Key.V, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Paste,
		[KeyGesture(Key.C, ModifierKeys.Control | ModifierKeys.Shift)] Edit_ShowClipboard,
		[KeyGesture(Key.F, ModifierKeys.Control)]  [KeyGesture(Key.F, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Find,
		[KeyGesture(Key.F3)]  [KeyGesture(Key.F3, ModifierKeys.Shift)] Edit_FindNext,
		[KeyGesture(Key.F3, ModifierKeys.Control)]  [KeyGesture(Key.F3, ModifierKeys.Control | ModifierKeys.Shift)] Edit_FindPrev,
		[KeyGesture(Key.G, ModifierKeys.Control)]  [KeyGesture(Key.G, ModifierKeys.Control | ModifierKeys.Shift)] Edit_GotoLine,
		Edit_GotoIndex,
		Files_Copy,
		Files_Cut,
		Files_Open,
		Files_Delete,
		Files_Timestamp_Write,
		Files_Timestamp_Access,
		Files_Timestamp_Create,
		Files_Timestamp_All,
		Files_Path_Simplify,
		Files_Path_GetFileName,
		Files_Path_GetFileNameWoExtension,
		Files_Path_GetDirectory,
		Files_Path_GetExtension,
		Files_CreateDirectory,
		Files_Information_Size,
		Files_Information_WriteTime,
		Files_Information_AccessTime,
		Files_Information_CreateTime,
		Files_Information_Attributes,
		Files_Information_ReadOnly,
		Files_Checksum_MD5,
		Files_Checksum_SHA1,
		Files_Checksum_SHA256,
		Files_Select_Existing,
		Files_Select_Files,
		Files_Select_Directories,
		Files_Select_Roots,
		Files_RenameKeysToSelections,
		[KeyGesture(Key.U, ModifierKeys.Control)] Data_Case_Upper,
		[KeyGesture(Key.U, ModifierKeys.Control | ModifierKeys.Shift)] Data_Case_Lower,
		Data_Case_Proper,
		Data_Case_Toggle,
		[KeyGesture(Key.H, ModifierKeys.Control)] Data_Hex_ToHex,
		[KeyGesture(Key.H, ModifierKeys.Control | ModifierKeys.Shift)] Data_Hex_FromHex,
		Data_Binary_ToBinary_UTF8,
		Data_Binary_ToBinary_UTF7,
		Data_Binary_ToBinary_UTF16LE,
		Data_Binary_ToBinary_UTF16BE,
		Data_Binary_ToBinary_UTF32LE,
		Data_Binary_ToBinary_UTF32BE,
		Data_Binary_ToBinary_Base64,
		Data_Binary_ToBinary_UInt8LE,
		Data_Binary_ToBinary_UInt16LE,
		Data_Binary_ToBinary_UInt32LE,
		Data_Binary_ToBinary_UInt64LE,
		Data_Binary_ToBinary_Int8LE,
		Data_Binary_ToBinary_Int16LE,
		Data_Binary_ToBinary_Int32LE,
		Data_Binary_ToBinary_Int64LE,
		Data_Binary_ToBinary_UInt8BE,
		Data_Binary_ToBinary_UInt16BE,
		Data_Binary_ToBinary_UInt32BE,
		Data_Binary_ToBinary_UInt64BE,
		Data_Binary_ToBinary_Int8BE,
		Data_Binary_ToBinary_Int16BE,
		Data_Binary_ToBinary_Int32BE,
		Data_Binary_ToBinary_Int64BE,
		Data_Binary_ToBinary_Single,
		Data_Binary_ToBinary_Double,
		Data_Binary_FromBinary_Auto,
		Data_Binary_FromBinary_UTF8,
		Data_Binary_FromBinary_UTF7,
		Data_Binary_FromBinary_UTF16LE,
		Data_Binary_FromBinary_UTF16BE,
		Data_Binary_FromBinary_UTF32LE,
		Data_Binary_FromBinary_UTF32BE,
		Data_Binary_FromBinary_Base64,
		Data_Binary_FromBinary_UInt8LE,
		Data_Binary_FromBinary_UInt16LE,
		Data_Binary_FromBinary_UInt32LE,
		Data_Binary_FromBinary_UInt64LE,
		Data_Binary_FromBinary_Int8LE,
		Data_Binary_FromBinary_Int16LE,
		Data_Binary_FromBinary_Int32LE,
		Data_Binary_FromBinary_Int64LE,
		Data_Binary_FromBinary_UInt8BE,
		Data_Binary_FromBinary_UInt16BE,
		Data_Binary_FromBinary_UInt32BE,
		Data_Binary_FromBinary_UInt64BE,
		Data_Binary_FromBinary_Int8BE,
		Data_Binary_FromBinary_Int16BE,
		Data_Binary_FromBinary_Int32BE,
		Data_Binary_FromBinary_Int64BE,
		Data_Binary_FromBinary_Single,
		Data_Binary_FromBinary_Double,
		Data_Base64_ToBase64_UTF8,
		Data_Base64_ToBase64_UTF7,
		Data_Base64_ToBase64_UTF16LE,
		Data_Base64_ToBase64_UTF16BE,
		Data_Base64_ToBase64_UTF32LE,
		Data_Base64_ToBase64_UTF32BE,
		Data_Base64_ToBase64_Binary,
		Data_Base64_FromBase64_Auto,
		Data_Base64_FromBase64_UTF8,
		Data_Base64_FromBase64_UTF7,
		Data_Base64_FromBase64_UTF16LE,
		Data_Base64_FromBase64_UTF16BE,
		Data_Base64_FromBase64_UTF32LE,
		Data_Base64_FromBase64_UTF32BE,
		Data_Base64_FromBase64_Binary,
		Data_DateTime_Insert,
		Data_DateTime_Convert,
		Data_Length,
		Data_Width,
		Data_Trim,
		[KeyGesture(Key.E, ModifierKeys.Control)] Data_EvaluateExpression,
		Data_Series,
		[KeyGesture(Key.D, ModifierKeys.Control)] Data_CopyDown,
		Data_Copy_Count,
		Data_Copy_Min_String,
		Data_Copy_Min_Numeric,
		Data_Copy_Max_String,
		Data_Copy_Max_Numeric,
		Data_Copy_Length_Min,
		Data_Copy_Length_Max,
		Data_Copy_Sum,
		[KeyGesture(Key.R, ModifierKeys.Control)] Data_Repeat,
		Data_GUID,
		Data_Random,
		Data_Escape_XML,
		Data_Escape_Regex,
		Data_Escape_URL,
		Data_Unescape_XML,
		Data_Unescape_Regex,
		Data_Unescape_URL,
		Data_MD5_UTF8,
		Data_MD5_UTF7,
		Data_MD5_UTF16LE,
		Data_MD5_UTF16BE,
		Data_MD5_UTF32LE,
		Data_MD5_UTF32BE,
		Data_SHA1_UTF8,
		Data_SHA1_UTF7,
		Data_SHA1_UTF16LE,
		Data_SHA1_UTF16BE,
		Data_SHA1_UTF32LE,
		Data_SHA1_UTF32BE,
		Data_SHA256_UTF8,
		Data_SHA256_UTF7,
		Data_SHA256_UTF16LE,
		Data_SHA256_UTF16BE,
		Data_SHA256_UTF32LE,
		Data_SHA256_UTF32BE,
		Sort_String,
		Sort_Numeric,
		Sort_Keys,
		Sort_Reverse,
		Sort_Randomize,
		Sort_Length,
		Sort_Lines_String,
		Sort_Lines_Numeric,
		Sort_Lines_Keys,
		Sort_Lines_Reverse,
		Sort_Lines_Randomize,
		Sort_Lines_Length,
		Sort_Regions_String,
		Sort_Regions_Numeric,
		Sort_Regions_Keys,
		Sort_Regions_Reverse,
		Sort_Regions_Randomize,
		Sort_Regions_Length,
		[KeyGesture(Key.K, ModifierKeys.Control | ModifierKeys.Shift)] Keys_SetKeys,
		[KeyGesture(Key.D1, ModifierKeys.Control | ModifierKeys.Shift)] Keys_SetValues1,
		[KeyGesture(Key.D2, ModifierKeys.Control | ModifierKeys.Shift)] Keys_SetValues2,
		[KeyGesture(Key.D3, ModifierKeys.Control | ModifierKeys.Shift)] Keys_SetValues3,
		[KeyGesture(Key.D4, ModifierKeys.Control | ModifierKeys.Shift)] Keys_SetValues4,
		[KeyGesture(Key.D5, ModifierKeys.Control | ModifierKeys.Shift)] Keys_SetValues5,
		[KeyGesture(Key.D6, ModifierKeys.Control | ModifierKeys.Shift)] Keys_SetValues6,
		[KeyGesture(Key.D7, ModifierKeys.Control | ModifierKeys.Shift)] Keys_SetValues7,
		[KeyGesture(Key.D8, ModifierKeys.Control | ModifierKeys.Shift)] Keys_SetValues8,
		[KeyGesture(Key.D9, ModifierKeys.Control | ModifierKeys.Shift)] Keys_SetValues9,
		[KeyGesture(Key.D1, ModifierKeys.Control)] Keys_SelectionReplace1,
		[KeyGesture(Key.D2, ModifierKeys.Control)] Keys_SelectionReplace2,
		[KeyGesture(Key.D3, ModifierKeys.Control)] Keys_SelectionReplace3,
		[KeyGesture(Key.D4, ModifierKeys.Control)] Keys_SelectionReplace4,
		[KeyGesture(Key.D5, ModifierKeys.Control)] Keys_SelectionReplace5,
		[KeyGesture(Key.D6, ModifierKeys.Control)] Keys_SelectionReplace6,
		[KeyGesture(Key.D7, ModifierKeys.Control)] Keys_SelectionReplace7,
		[KeyGesture(Key.D8, ModifierKeys.Control)] Keys_SelectionReplace8,
		[KeyGesture(Key.D9, ModifierKeys.Control)] Keys_SelectionReplace9,
		Keys_GlobalFindKeys,
		Keys_GlobalFind1,
		Keys_GlobalFind2,
		Keys_GlobalFind3,
		Keys_GlobalFind4,
		Keys_GlobalFind5,
		Keys_GlobalFind6,
		Keys_GlobalFind7,
		Keys_GlobalFind8,
		Keys_GlobalFind9,
		Keys_GlobalReplace1,
		Keys_GlobalReplace2,
		Keys_GlobalReplace3,
		Keys_GlobalReplace4,
		Keys_GlobalReplace5,
		Keys_GlobalReplace6,
		Keys_GlobalReplace7,
		Keys_GlobalReplace8,
		Keys_GlobalReplace9,
		Keys_CopyKeys,
		Keys_CopyValues1,
		Keys_CopyValues2,
		Keys_CopyValues3,
		Keys_CopyValues4,
		Keys_CopyValues5,
		Keys_CopyValues6,
		Keys_CopyValues7,
		Keys_CopyValues8,
		Keys_CopyValues9,
		Keys_HitsKeys,
		Keys_HitsValues1,
		Keys_HitsValues2,
		Keys_HitsValues3,
		Keys_HitsValues4,
		Keys_HitsValues5,
		Keys_HitsValues6,
		Keys_HitsValues7,
		Keys_HitsValues8,
		Keys_HitsValues9,
		Keys_MissesKeys,
		Keys_MissesValues1,
		Keys_MissesValues2,
		Keys_MissesValues3,
		Keys_MissesValues4,
		Keys_MissesValues5,
		Keys_MissesValues6,
		Keys_MissesValues7,
		Keys_MissesValues8,
		Keys_MissesValues9,
		Keys_Counts,
		[KeyGesture(Key.M, ModifierKeys.Control)] SelectMark_Toggle,
		[KeyGesture(Key.A, ModifierKeys.Control)] Select_All,
		Select_Limit,
		[KeyGesture(Key.L, ModifierKeys.Control)] Select_Lines,
		Select_NonEmpty,
		Select_Marks,
		Select_Find,
		Select_Unique,
		Select_Duplicates,
		Select_Min_String,
		Select_Min_Numeric,
		Select_Max_String,
		Select_Max_Numeric,
		Select_ExpressionMatches,
		Select_RegExMatches,
		[KeyGesture(Key.D0, ModifierKeys.Alt)] Select_ShowFirst,
		[KeyGesture(Key.Space, ModifierKeys.Alt)]  [KeyGesture(Key.Space, ModifierKeys.Control)] Select_ShowCurrent,
		[KeyGesture(Key.Down, ModifierKeys.Alt)] Select_NextSelection,
		[KeyGesture(Key.Up, ModifierKeys.Alt)] Select_PrevSelection,
		[KeyGesture(Key.Enter, ModifierKeys.Alt)] Select_Single,
		[KeyGesture(Key.OemMinus, ModifierKeys.Alt)] Select_Remove,
		Mark_Selection,
		Mark_Find,
		Mark_Clear,
		Mark_LimitToSelection,
		View_Highlighting_None,
		View_Highlighting_CSharp,
		View_Highlighting_CPlusPlus,
		View_Tiles,
	}
}
