using System;
using System.Windows.Input;
using NeoEdit.GUI.Controls;

namespace NeoEdit.TextEdit
{
	enum TextEditCommand
	{
		None,
		[KeyGesture(Key.N, ModifierKeys.Control)] [KeyGesture(Key.N, ModifierKeys.Control | ModifierKeys.Shift, false)] File_New,
		[KeyGesture(Key.O, ModifierKeys.Control)] File_Open_Open,
		[KeyGesture(Key.O, ModifierKeys.Control | ModifierKeys.Alt)] [KeyGesture(Key.O, ModifierKeys.Control | ModifierKeys.Shift, false)] File_Open_CopiedCut,
		File_Open_Selected,
		[KeyGesture(Key.S, ModifierKeys.Control)] File_Save_Save,
		File_Save_SaveAs,
		File_Operations_Rename,
		File_Operations_Delete,
		File_Operations_Explore,
		File_Operations_Encryption,
		[KeyGesture(Key.F4, ModifierKeys.Control)] File_Close,
		[KeyGesture(Key.F5)] File_Refresh,
		File_Revert,
		File_Insert_Files,
		File_Insert_CopiedCut,
		File_Insert_Selected,
		File_Copy_Path,
		File_Copy_Name,
		File_Copy_AllPaths,
		File_Copy_Count,
		File_Encoding_Encoding,
		File_Encoding_ReopenWithEncoding,
		[KeyGesture(Key.H, ModifierKeys.Control | ModifierKeys.Alt)] File_HexEditor,
		File_Exit,
		[KeyGesture(Key.Z, ModifierKeys.Control)] Edit_Undo,
		[KeyGesture(Key.Z, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Redo,
		[KeyGesture(Key.C, ModifierKeys.Control)] Edit_Copy_Copy,
		[KeyGesture(Key.C, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift)] Edit_Copy_AllFiles,
		[KeyGesture(Key.X, ModifierKeys.Control)] Edit_Copy_Cut,
		[KeyGesture(Key.V, ModifierKeys.Control)] [KeyGesture(Key.V, ModifierKeys.Control | ModifierKeys.Shift, false)] Edit_Paste_Paste,
		[KeyGesture(Key.V, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift)] Edit_Paste_AllFiles,
		Edit_Diff_Diff,
		Edit_Diff_Break,
		[KeyGesture(Key.Down, ModifierKeys.Alt)] Edit_Diff_Next,
		[KeyGesture(Key.Up, ModifierKeys.Alt)] Edit_Diff_Previous,
		[KeyGesture(Key.Left, ModifierKeys.Alt)] Edit_Diff_CopyLeft,
		[KeyGesture(Key.Right, ModifierKeys.Alt)] Edit_Diff_CopyRight,
		[KeyGesture(Key.F, ModifierKeys.Control)] [KeyGesture(Key.F, ModifierKeys.Control | ModifierKeys.Shift, false)] Edit_Find_Find,
		[KeyGesture(Key.F3)] [KeyGesture(Key.F3, ModifierKeys.Shift, false)] Edit_Find_Next,
		[KeyGesture(Key.F3, ModifierKeys.Control)] [KeyGesture(Key.F3, ModifierKeys.Control | ModifierKeys.Shift, false)] Edit_Find_Previous,
		Edit_Find_Replace,
		Edit_Table_ToTable,
		Edit_Table_RegionsSelectionsToTable,
		Edit_Table_FromTable,
		[KeyGesture(Key.D, ModifierKeys.Control)] Edit_CopyDown,
		[KeyGesture(Key.R, ModifierKeys.Control)] Edit_Repeat,
		Edit_Markup_Escape,
		Edit_Markup_Unescape,
		Edit_RegEx_Escape,
		Edit_RegEx_Unescape,
		Edit_URL_Escape,
		Edit_URL_Unescape,
		Edit_URL_Fetch,
		Edit_URL_Absolute,
		Edit_Hash_MD5,
		Edit_Hash_SHA1,
		Edit_Hash_SHA256,
		[KeyGesture(Key.S, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Sort,
		[KeyGesture(Key.A, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Aggregate,
		[KeyGesture(Key.C, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Convert,
		[KeyGesture(Key.F2, ModifierKeys.Alt)] Edit_Bookmarks_Toggle,
		[KeyGesture(Key.F2)] [KeyGesture(Key.F2, ModifierKeys.Shift, false)] Edit_Bookmarks_Next,
		[KeyGesture(Key.F2, ModifierKeys.Control)] [KeyGesture(Key.F2, ModifierKeys.Control | ModifierKeys.Shift, false)] Edit_Bookmarks_Previous,
		Edit_Bookmarks_Clear,
		Files_Create_Files,
		Files_Create_Directories,
		Files_Names_Simplify,
		Files_Names_MakeAbsolute,
		Files_Names_GetUnique,
		Files_Names_Sanitize,
		Files_Get_Size,
		Files_Get_WriteTime,
		Files_Get_AccessTime,
		Files_Get_CreateTime,
		Files_Get_Attributes,
		Files_Set_Size,
		Files_Set_WriteTime,
		Files_Set_AccessTime,
		Files_Set_CreateTime,
		Files_Set_AllTimes,
		Files_Set_Attributes,
		Files_Select_Name_Directory,
		Files_Select_Name_Name,
		Files_Select_Name_FileNamewoExtension,
		Files_Select_Name_Extension,
		Files_Select_Files,
		Files_Select_Directories,
		Files_Select_Existing,
		Files_Select_NonExisting,
		Files_Select_Roots,
		Files_Select_NonRoots,
		Files_Hash_MD5,
		Files_Hash_SHA1,
		Files_Hash_SHA256,
		Files_Operations_Copy,
		Files_Operations_Move,
		Files_Operations_Delete,
		Files_Operations_SaveClipboards,
		Files_Operations_DragDrop,
		Files_Operations_OpenDisk,
		[KeyGesture(Key.E, ModifierKeys.Control)] Expression_Expression,
		Expression_Copy,
		[KeyGesture(Key.E, ModifierKeys.Control | ModifierKeys.Shift)] Expression_EvaluateSelected,
		Expression_SelectByExpression,
		Text_Copy_Length,
		Text_Copy_Min_Text,
		Text_Copy_Min_Length,
		Text_Copy_Max_Text,
		Text_Copy_Max_Length,
		Text_Select_Trim,
		Text_Select_ByWidth,
		Text_Select_Min_Text,
		Text_Select_Min_Length,
		Text_Select_Max_Text,
		Text_Select_Max_Length,
		[KeyGesture(Key.U, ModifierKeys.Control | ModifierKeys.Shift)] Text_Case_Upper,
		[KeyGesture(Key.U, ModifierKeys.Control)] Text_Case_Lower,
		Text_Case_Proper,
		Text_Case_Toggle,
		Text_Length,
		[KeyGesture(Key.W, ModifierKeys.Control)] Text_Width,
		[KeyGesture(Key.T, ModifierKeys.Control)] Text_Trim,
		Text_SingleLine,
		Text_GUID,
		Text_RandomText,
		Text_ReverseRegEx,
		Text_CombinationsPermutations,
		Numeric_Copy_Min,
		Numeric_Copy_Max,
		Numeric_Copy_Sum,
		Numeric_Select_Min,
		Numeric_Select_Max,
		[KeyGesture(Key.H, ModifierKeys.Control)] Numeric_Hex_ToHex,
		[KeyGesture(Key.H, ModifierKeys.Control | ModifierKeys.Shift)] Numeric_Hex_FromHex,
		Numeric_Series,
		Numeric_RandomNumber,
		Numeric_MinMaxValues,
		DateTime_Now,
		DateTime_Convert,
		[KeyGesture(Key.G, ModifierKeys.Control)] [KeyGesture(Key.G, ModifierKeys.Control | ModifierKeys.Shift, false)] Position_Goto_Lines,
		Position_Goto_Columns,
		Position_Goto_Positions,
		Position_Copy_Lines,
		Position_Copy_Columns,
		Position_Copy_Positions,
		Content_Reformat,
		Content_Comment,
		Content_Uncomment,
		[KeyGesture(Key.OemCloseBrackets, ModifierKeys.Control | ModifierKeys.Alt)] [KeyGesture(Key.OemCloseBrackets, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift)] Content_TogglePosition,
		[KeyGesture(Key.Left, ModifierKeys.Control | ModifierKeys.Alt)] [KeyGesture(Key.Left, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift, false)] Content_Parent,
		Content_Ancestor,
		Content_Attributes_Attributes,
		Content_Attributes_First,
		Content_Attributes_ByAttribute,
		[KeyGesture(Key.Right, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift)] Content_Children_Children,
		Content_Children_SelfAndChildren,
		[KeyGesture(Key.Right, ModifierKeys.Control | ModifierKeys.Alt)] Content_Children_First,
		Content_Children_ByAttribute,
		Content_Descendants_Descendants,
		Content_Descendants_SelfAndDescendants,
		Content_Descendants_First,
		Content_Descendants_ByAttribute,
		[KeyGesture(Key.Down, ModifierKeys.Control | ModifierKeys.Alt)] [KeyGesture(Key.Down, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift, false)] Content_Next,
		[KeyGesture(Key.Up, ModifierKeys.Control | ModifierKeys.Alt)] [KeyGesture(Key.Up, ModifierKeys.Control | ModifierKeys.Alt | ModifierKeys.Shift, false)] Content_Previous,
		Content_Select_ByAttribute,
		Content_Select_Topmost,
		Content_Select_Deepest,
		Content_Select_MaxTopmost,
		Content_Select_MaxDeepest,
		[KeyGesture(Key.K, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Keys,
		[KeyGesture(Key.D1, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values1,
		[KeyGesture(Key.D2, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values2,
		[KeyGesture(Key.D3, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values3,
		[KeyGesture(Key.D4, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values4,
		[KeyGesture(Key.D5, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values5,
		[KeyGesture(Key.D6, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values6,
		[KeyGesture(Key.D7, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values7,
		[KeyGesture(Key.D8, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values8,
		[KeyGesture(Key.D9, ModifierKeys.Control | ModifierKeys.Shift)] Keys_Set_Values9,
		Keys_Add_Keys,
		Keys_Add_Values1,
		Keys_Add_Values2,
		Keys_Add_Values3,
		Keys_Add_Values4,
		Keys_Add_Values5,
		Keys_Add_Values6,
		Keys_Add_Values7,
		Keys_Add_Values8,
		Keys_Add_Values9,
		[KeyGesture(Key.D1, ModifierKeys.Control)] Keys_Replace_Values1,
		[KeyGesture(Key.D2, ModifierKeys.Control)] Keys_Replace_Values2,
		[KeyGesture(Key.D3, ModifierKeys.Control)] Keys_Replace_Values3,
		[KeyGesture(Key.D4, ModifierKeys.Control)] Keys_Replace_Values4,
		[KeyGesture(Key.D5, ModifierKeys.Control)] Keys_Replace_Values5,
		[KeyGesture(Key.D6, ModifierKeys.Control)] Keys_Replace_Values6,
		[KeyGesture(Key.D7, ModifierKeys.Control)] Keys_Replace_Values7,
		[KeyGesture(Key.D8, ModifierKeys.Control)] Keys_Replace_Values8,
		[KeyGesture(Key.D9, ModifierKeys.Control)] Keys_Replace_Values9,
		Keys_Find_Keys,
		Keys_Find_Values1,
		Keys_Find_Values2,
		Keys_Find_Values3,
		Keys_Find_Values4,
		Keys_Find_Values5,
		Keys_Find_Values6,
		Keys_Find_Values7,
		Keys_Find_Values8,
		Keys_Find_Values9,
		Keys_Copy_Keys,
		Keys_Copy_Values1,
		Keys_Copy_Values2,
		Keys_Copy_Values3,
		Keys_Copy_Values4,
		Keys_Copy_Values5,
		Keys_Copy_Values6,
		Keys_Copy_Values7,
		Keys_Copy_Values8,
		Keys_Copy_Values9,
		Keys_Hits_Keys,
		Keys_Hits_Values1,
		Keys_Hits_Values2,
		Keys_Hits_Values3,
		Keys_Hits_Values4,
		Keys_Hits_Values5,
		Keys_Hits_Values6,
		Keys_Hits_Values7,
		Keys_Hits_Values8,
		Keys_Hits_Values9,
		Keys_Misses_Keys,
		Keys_Misses_Values1,
		Keys_Misses_Values2,
		Keys_Misses_Values3,
		Keys_Misses_Values4,
		Keys_Misses_Values5,
		Keys_Misses_Values6,
		Keys_Misses_Values7,
		Keys_Misses_Values8,
		Keys_Misses_Values9,
		[KeyGesture(Key.A, ModifierKeys.Control)] Select_All,
		Select_Limit,
		[KeyGesture(Key.L, ModifierKeys.Control)] Select_Lines,
		Select_Empty,
		Select_NonEmpty,
		Select_Unique,
		Select_Duplicates,
		Select_ByCount,
		Select_Regions,
		Select_FindResults,
		[KeyGesture(Key.D0, ModifierKeys.Alt)] Select_Selection_First,
		[KeyGesture(Key.Space, ModifierKeys.Alt)] Select_Selection_ShowCurrent,
		[KeyGesture(Key.OemPlus, ModifierKeys.Alt)] Select_Selection_Next,
		[KeyGesture(Key.OemMinus, ModifierKeys.Alt)] Select_Selection_Previous,
		[KeyGesture(Key.Enter, ModifierKeys.Alt)] Select_Selection_Single,
		[KeyGesture(Key.Back, ModifierKeys.Alt)] Select_Selection_Remove,
		[KeyGesture(Key.M, ModifierKeys.Control)] Region_ToggleRegionsSelections,
		Region_SetSelection,
		Region_SetFindResults,
		Region_ClearRegions,
		Region_LimitToSelection,
		Region_SelectEnclosingRegion,
		View_ActiveTabs,
		View_WordList,
		[KeyGesture(Key.R, ModifierKeys.Control | ModifierKeys.Shift)] Macro_Record_QuickRecord,
		Macro_Record_Record,
		Macro_Record_StopRecording,
		[KeyGesture(Key.P, ModifierKeys.Control | ModifierKeys.Shift)] Macro_Play_QuickPlay,
		Macro_Play_Play,
		Macro_Play_Repeat,
		Macro_Play_PlayOnCopiedFiles,
		Macro_Open_Quick,
		Macro_Open_Open,
		[KeyGesture(Key.OemPeriod, ModifierKeys.Control)] Macro_RepeatLastAction,
		Macro_TimeNextAction,
	}
}
