using System.Windows.Input;
using NeoEdit.GUI.Common;

namespace NeoEdit.BinaryEditor
{
	class BinaryEditMenuItem : NEMenuItem<BinaryEditCommand> { }

	enum BinaryEditCommand
	{
		None,
		[KeyGesture(Key.N, ModifierKeys.Control)] [KeyGesture(Key.T, ModifierKeys.Control)] File_New,
		[KeyGesture(Key.O, ModifierKeys.Control)] File_Open,
		File_OpenDump,
		File_OpenCopied,
		[KeyGesture(Key.S, ModifierKeys.Control)] File_Save,
		File_SaveAs,
		[KeyGesture(Key.F4, ModifierKeys.Control)] [KeyGesture(Key.W, ModifierKeys.Control)] File_Close,
		File_CopyPath,
		File_CopyName,
		File_Encode_Auto,
		File_Encode_UTF8,
		File_Encode_UTF7,
		File_Encode_UTF16LE,
		File_Encode_UTF16BE,
		File_Encode_UTF32LE,
		File_Encode_UTF32BE,
		File_Encode_Base64,
		File_Encode_Hex,
		[KeyGesture(Key.T, ModifierKeys.Control | ModifierKeys.Alt)] File_TextEditor,
		File_Exit,
		[KeyGesture(Key.Z, ModifierKeys.Control)] Edit_Undo,
		[KeyGesture(Key.Z, ModifierKeys.Control | ModifierKeys.Shift)] Edit_Redo,
		[KeyGesture(Key.X, ModifierKeys.Control)] Edit_Cut,
		[KeyGesture(Key.C, ModifierKeys.Control)] Edit_Copy,
		[KeyGesture(Key.V, ModifierKeys.Control)] Edit_Paste,
		[KeyGesture(Key.C, ModifierKeys.Control | ModifierKeys.Shift)] Edit_ShowClipboard,
		[KeyGesture(Key.F, ModifierKeys.Control)] Edit_Find,
		[KeyGesture(Key.F3)] Edit_FindNext,
		[KeyGesture(Key.F3, ModifierKeys.Shift)] Edit_FindPrev,
		[KeyGesture(Key.G, ModifierKeys.Control)] Edit_Goto,
		[KeyGesture(Key.Insert)] Edit_Insert,
		View_Values,
		[KeyGesture(Key.F5)] View_Refresh,
		View_Tiles,
		Checksum_MD5,
		Checksum_SHA1,
		Checksum_SHA256,
		Compress_GZip,
		Compress_Deflate,
		Decompress_GZip,
		Decompress_Inflate,
		Encrypt_AES,
		Encrypt_DES,
		Encrypt_DES3,
		Encrypt_RSA,
		Encrypt_RSAAES,
		Decrypt_AES,
		Decrypt_DES,
		Decrypt_DES3,
		Decrypt_RSA,
		Decrypt_RSAAES,
		Sign_RSA,
		Sign_DSA,
		Verify_RSA,
		Verify_DSA,
		Data_Fill,
	}
}
